networks:
    inception:
        name: "inception"
        driver: "bridge"

services:
    nginx:
        container_name: nginx
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        image: nginx:fromScratch
        networks:
            - inception
        ports:
            - "443:443"
        depends_on:
            - wordpress
        volumes:
            - /home/artclave/data:/var/www/artclave.42.fr
        # restart: always
    wordpress:
        container_name: wordpress
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        image: wordpress:fromScratch
        networks: 
            - inception
        volumes:
            - /home/artclave/data:/var/www/artclave.42.fr
        environment:
            DB_NAME: ${DB_NAME}
            DB_ADMIN: ${DB_ADMIN}
            DB_ADMIN_PW: ${DB_ADMIN_PW}
            DB_ROOT_PW: ${DB_ROOT_PW}
        depends_on:
            - mariadb
        # restart: always
    mariadb:
        container_name: mariadb
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        image: mariadb:fromScratch
        networks:
            - inception
        environment:
            DB_NAME: ${DB_NAME}
            DB_ADMIN: ${DB_ADMIN}
            DB_ADMIN_PW: ${DB_ADMIN_PW}
            DB_ROOT_PW: ${DB_ROOT_PW}
        #ADD VOLUME!
        # restart: always
