networks:
    inception:
        name: "inception"
        driver: "bridge"

services:
    nginx:
        container_name: nginx
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        image: nginx:fromScratch
        networks:
            - inception
        ports:
            - "8443:443"
        depends_on:
            - wordpress
        volumes:
            - page:/var/www/$DOMAIN_NAME
        environment:
            - DOMAIN_NAME=$DOMAIN_NAME
        restart: unless-stopped
    wordpress:
        container_name: wordpress
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        image: wordpress:fromScratch
        networks: 
            - inception
        volumes:
            - page:/var/www/$DOMAIN_NAME
        environment:
            - DOMAIN_NAME=$DOMAIN_NAME
        secrets:
            - db_name
            - db_admin
            - db_admin_pw
            - wp_admin
            - wp_admin_email 
            - wp_admin_pw
            - wp_user
            - wp_user_role
            - wp_user_email
            - wp_user_pw

        depends_on:
            - mariadb
        restart: unless-stopped
    mariadb:
        container_name: mariadb
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        image: mariadb:fromScratch
        networks:
            - inception
        secrets:
            - db_name
            - db_admin
            - db_admin_pw 
            - db_root_pw
        volumes:
            - database:/var/lib/mysql
        restart: on-failure
secrets:
    db_root_pw:
        environment: DB_ROOT_PW
    db_name:
        environment: DB_NAME
    db_admin:
        environment: DB_ADMIN
    db_admin_pw:
        environment: DB_ADMIN_PW
    wp_admin:
        environment: WP_ADMIN
    wp_admin_pw:
        environment: WP_ADMIN_PW
    wp_admin_email:
        environment: WP_ADMIN_EMAIL
    wp_user:
        environment: WP_USER2
    wp_user_role:
        environment: WP_USER2_ROLE
    wp_user_email:
        environment: WP_USER2_EMAIL
    wp_user_pw:
        environment: WP_USER2_PW

volumes:
    page:
        driver: local
        driver_opts:
            type: none
            device: /home/artclave/data/website
            o: bind
    database:
        driver: local
        driver_opts:
            type: none
            device: /home/artclave/data/database
            o: bind
