
-- VERSION 1!
-- CREATE DATABASE $DB_NAME;
-- CREATE USER '$DB_ADMIN'@'localhost' IDENTIFIED BY '$DB_ADMIN_PW';
-- GRANT ALL PRIVILEGES ON wordpress.* TO '$DB_ADMIN'@'%' IDENTIFIED BY '$DB_ADMIN_PW';
-- ALTER USER 'root'@'localhost' IDENTIFIED BY '$DB_ROOT_PW';
-- FLUSH PRIVILEGES;


-- VERSION 2!
-- CREATE DATABASE IF NOT EXISTS $DB_NAME;
-- CREATE USER IF NOT EXISTS '$DB_ADMIN'@'localhost' IDENTIFIED BY '$DB_ADMIN_PW';
-- GRANT ALL PRIVILEGES ON wordpress.* TO '$DB_ADMIN'@'%' IDENTIFIED BY '$DB_ADMIN_PW';
-- ALTER USER 'root'@'localhost' IDENTIFIED BY '$DB_ROOT_PW';
-- FLUSH PRIVILEGES;

-- VERSION 3!
CREATE DATABASE IF NOT EXISTS $DB_NAME;
CREATE USER IF NOT EXISTS '$DB_ADMIN'@'localhost' IDENTIFIED BY '$DB_ADMIN_PW';
SELECT GRANTEE 
FROM information_schema.USER_PRIVILEGES 
WHERE TABLE_SCHEMA = '$DB_NAME' AND GRANTEE != 'root'@'localhost';
REVOKE ALL PRIVILEGES ON $DB_NAME.* FROM '<user>@localhost';
GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_ADMIN'@'localhost';
ALTER USER 'root'@'localhost' IDENTIFIED BY '$DB_ROOT_PW';
FLUSH PRIVILEGES;
