CREATE DATABASE $DB_NAME;
CREATE USER '$DB_ADMIN'@'localhost' IDENTIFIED BY '$DB_ADMIN_PW';
GRANT ALL PRIVILEGES ON wordpress.* TO '$DB_ADMIN'@'%' IDENTIFIED BY '$DB_ADMIN_PW';
ALTER USER 'root'@'localhost' IDENTIFIED BY '$DB_ROOT_PW';
FLUSH PRIVILEGES;